// src/components/GuideTemplate/guideStyles.js

export const guideStyles = {
  container: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    color: '#334155',
    backgroundColor: '#f8fafc',
    minHeight: '100vh',
    paddingBottom: '4rem',
  },
  hero: {
    position: 'relative',
    backgroundColor: '#0f172a',
    color: '#ffffff',
    padding: '5rem 1.5rem',
    textAlign: 'center',
    overflow: 'hidden',
  },
  heroBg: {
    position: 'absolute',
    inset: 0,
    opacity: 0.3,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
  },
  heroContent: {
    position: 'relative',
    zIndex: 10,
    maxWidth: '800px',
    margin: '0 auto',
  },
  badge: {
    backgroundColor: '#f59e0b',
    color: '#0f172a',
    padding: '0.25rem 0.75rem',
    borderRadius: '9999px',
    fontSize: '0.875rem',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    display: 'inline-block',
  },
  h1: {
    fontSize: '2.5rem',
    fontWeight: '800',
    marginTop: '1rem',
    marginBottom: '1.5rem',
    lineHeight: '1.2',
  },
  heroDesc: {
    fontSize: '1.125rem',
    color: '#e2e8f0',
    lineHeight: '1.6',
  },
  main: {
    maxWidth: '800px',
    margin: '3rem auto 0 auto',
    padding: '0 1rem',
  },
  articleCard: {
    backgroundColor: '#ffffff',
    borderRadius: '1rem',
    boxShadow:
      '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)',
    padding: '2.5rem',
    border: '1px solid #f1f5f9',
  },
  h2: {
    fontSize: '1.75rem',
    fontWeight: '700',
    color: '#0f172a',
    borderLeft: '4px solid #f59e0b',
    paddingLeft: '0.75rem',
    marginBottom: '1.5rem',
    marginTop: '2.5rem',
  },
  p: {
    fontSize: '1.05rem',
    lineHeight: '1.7',
    color: '#475569',
    marginBottom: '1.5rem',
  },
  tableWrapper: {
    overflowX: 'auto',
    margin: '1.5rem 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    backgroundColor: '#f1f5f9',
    color: '#334155',
    fontWeight: '600',
    padding: '0.75rem',
    border: '1px solid #e2e8f0',
  },
  td: {
    padding: '0.75rem',
    border: '1px solid #e2e8f0',
    color: '#475569',
  },
  ctaBox: {
    backgroundColor: '#f8fafc',
    padding: '1.5rem',
    borderRadius: '1rem',
    border: '1px solid #e2e8f0',
    margin: '2rem 0',
  },
  ctaHeader: {
    marginBottom: '1rem',
  },
  ctaBadge: {
    backgroundColor: '#dbeafe',
    color: '#1e40af',
    fontSize: '0.75rem',
    fontWeight: '600',
    padding: '0.125rem 0.5rem',
    borderRadius: '0.25rem',
  },
  ctaTitle: {
    fontSize: '1.25rem',
    fontWeight: '700',
    marginTop: '0.5rem',
    color: '#0f172a',
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '1rem',
    margin: '1.5rem 0',
  },
  gridCard: {
    backgroundColor: '#f8fafc',
    padding: '1.25rem',
    borderRadius: '0.75rem',
    border: '1px solid #f1f5f9',
  },
  gridCardTitle: {
    fontWeight: '700',
    fontSize: '1.1rem',
    color: '#0f172a',
    marginBottom: '0.5rem',
  },
  buttonDark: {
    backgroundColor: '#0f172a',
    color: '#ffffff',
    fontWeight: '700',
    padding: '0.75rem 1.25rem',
    borderRadius: '0.5rem',
    textDecoration: 'none',
    display: 'inline-block',
  },
  buttonGreen: {
    backgroundColor: '#059669',
    color: '#ffffff',
    fontWeight: '700',
    padding: '0.75rem 1.25rem',
    borderRadius: '0.5rem',
    textDecoration: 'none',
    display: 'inline-block',
  },
  timelineItem: {
    borderLeft: '2px solid #e2e8f0',
    paddingLeft: '1.5rem',
    position: 'relative',
    marginBottom: '1.5rem',
  },
  timelineDot: {
    position: 'absolute',
    left: '-9px',
    top: '4px',
    backgroundColor: '#f59e0b',
    width: '16px',
    height: '16px',
    borderRadius: '50%',
  },
  faqItem: {
    backgroundColor: '#f8fafc',
    padding: '1rem',
    borderRadius: '0.75rem',
    marginBottom: '1rem',
  },
  footerCta: {
    borderTop: '1px solid #f1f5f9',
    paddingTop: '2rem',
    textAlign: 'center',
    marginTop: '3rem',
  },
};
